zjmzxfzhl:
  redisson:
    config: '{
"sentinelServersConfig":{
    "idleConnectionTimeout":10000,
    "pingTimeout":1000,
    "connectTimeout":10000,
    "timeout":3000,
    "retryAttempts":3,
    "retryInterval":1500,
    "failedSlaveReconnectionInterval":3000,
    "failedSlaveCheckInterval":3
    "password":"zjmzxfzhl",
    "subscriptionsPerConnection":5,
    "clientName":null,
    "loadBalancer":{
        "class":"org.redisson.connection.balancer.RoundRobinLoadBalancer"
    },
    "slaveSubscriptionConnectionMinimumIdleSize":1,
    "slaveSubscriptionConnectionPoolSize":50,
    "slaveConnectionMinimumIdleSize":32,
    "slaveConnectionPoolSize":64,
    "masterConnectionMinimumIdleSize":32,
    "masterConnectionPoolSize":64,
    "readMode":"SLAVE",
    "sentinelAddresses":[
        "redis://172.172.222.101:26379",
        "redis://172.172.222.102:26379",
        "redis://172.172.222.103:26379"
    ],
    "masterName":"mymaster",
    "database":0
},
"threads":0,
"nettyThreads":0,
"codec":{
    "class":"org.redisson.codec.JsonJacksonCodec"
},
"transportMode":"NIO"
}'